name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: change file and restore
      run: |
        cd AudioSynth
        dotnet restore
    - name: change file and build
      run: |
        cd AudioSynth
        dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
